USE [master]
GO

/****** Object:  Database [HRMS]    Script Date: 14-12-2022 18:51:24 ******/
CREATE DATABASE [HRMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HRMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HRMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HRMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRMS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HRMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRMS] SET RECOVERY FULL 
GO

ALTER DATABASE [HRMS] SET  MULTI_USER 
GO

ALTER DATABASE [HRMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HRMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HRMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HRMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HRMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HRMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HRMS] SET  READ_WRITE 
GO

